server:
  port: 8001
  address: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${server.address}:8000/eureka/  # \u6307\u660E\u81EA\u5DF1\u7684\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740\u3002
spring:
  application:
    name: service-hi


