server:
  port: 8080
spring:
  datasource:
    name: micro-component-mybatis
    url: jdbc:mysql://127.0.0.1:3306/micro-component-mybatis
    username: root
    password: 123456
    # \u4F7F\u7528\u7684\u8FDE\u63A5\u6C60\u7684\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 6000
    minIdle: 1
    timeBetweenEvictionRunsMills: 3000
    validationQuery: select 'X'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fxb.mircro3componentmybatis
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
